
(defun grade (p)
  (cond ((>= p 90) "A+")
        ((>= p 85) "A")
        ((>= p 80) "A-")
        ((>= p 77) "B+")
        ((>= p 73) "B")
        ((>= p 70) "B-")
        ((>= p 0) "F")
        ((null p) "FNA")
        (t "Invalid percentage")))
